name: beatbuddy

services:
  catalog-ms:
    image: docker.io/vutiendat3601/beatbuddy-catalog-ms:latest
    container_name: catalog-ms
    hostname: catalog-ms
    environment:
      - SERVER_PORT=8010
    ports:
      - 8010:8010
    networks:
      - default

networks:
  default:
    name: beatbuddy
    driver: bridge
