version: '3.8'
name: bbcatalog

services:
  catalog-db:
    image: postgres:16.2-alpine3.19
    hostname: catalog-db
    environment:
      - POSTGRES_DB=beatbuddy_catalog
      - POSTGRES_USER=bbcatalogdb
      - POSTGRES_PASSWORD=bbcatalogdb
      - PGPASSWORD=bbcatalogdb
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - ./initdb.d/:/docker-entrypoint-initdb.d/

networks:
  default:
    name: bbcatalog
    driver: bridge
