spring:
  datasource:
    url: jdbc:postgresql://catalog-db:5432/beatbuddy_catalog
    username: bbcatalogdb
    password: bbcatalogdb
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
  jpa:
      show-sql: true
  devtools:
    livereload:
      enabled: true
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-discovery:8000/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
