server:
  port: 8010
  compression:
    enabled: true
spring:
  application:
    name: catalog
  devtools:
    livereload:
      enabled: false
      port: 0
    add-properties: false
  web:
    resources:
      add-mappings: false
springdoc:
  api-docs:
    enabled: true
    path: /apidocs
  swagger-ui:
    enabled: true
    path: /apidocs.html

client:
  user:
    url: http://user-ms:8000
  playlist:
    url: http://playlist-ms:8020
  artist:
    url: http://artist-ms:8040
  track:
    url: http://track-ms:8050

keycloak:
  authorization:
    client:
      authServerUrl: https://datvutech.io.vn/oauth
      realm: beatbuddy
      clientId: beatbuddy
      clientSecret: g3cQyG74X192BTW4bsr9jfV0kUTGnmG6
