server:
  port: 8010
spring:
  application:
    name: catalog
  devtools:
    livereload:
      enabled: false
      port: 0
client:
  artist:
    url: http://artist-ms:8040
  track:
    url: http://track-ms:8050
